
export const cards = {
  cards: [
    {
      "id": "0",
      "description": "Track 1",
      "heure": "",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "50px",
      "color": "#673ab7",
      "isCard": false,
      "users": []
    },
    {
      "id": "1",
      "description": "Track 2",
      "heure": "",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "50px",
      "color": "#ff8a80",
      "isCard": false,
      "users": []
    },
    {
      "id": "2",
      "description": "Track 3",
      "heure": "",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "50px",
      "color": "#26a69a",
      "isCard": false,
      "users": []
    },
    {
      "id": "3",
      "description": "ACCUEIL",
      "heure": "9H00",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "60px",
      "color": "darkgreen",
      "isCard": false,
      "users": []
    },
    {
      "id": "4",
      "description": "KEYNOTE",
      "heure": "9H25",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "60px",
      "color": "#ff9800",
      "isCard": false,
      "users": []
    },
    {
      "id": "5",
      "description": "The Role of the State in Enabling Innovation",
      "heure": "9H40",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "60px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Neil",
          "username": "GIBBONS",
          "companyPosition": "Backend Engineer",
          "company": "EDITED",
          "GDE": "Non",
          "Charges": "110\u20ac",
          "picturePath": "assets/images/Neil Gibbons.jpeg",
          "city": "London",
          "country": "UK",
          "email": "neil.gibbons64@gmail.com",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": "https://github.com/nyptop"
        },
      ]
    },
    {
      "id": "6",
      "description": "BREAK",
      "heure": "10H20",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "60px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "7",
      "description": "Workshop: Flutter app Journey from Mobile to Web and Desktop",
      "heure": "10H30",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "365px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Alexander",
          "username": "EFREMENKOV",
          "companyPosition": "Senior Android Engineer",
          "company": "Bolt",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/Alexander Efremenkov.jpeg",
          "city": "Tallinn",
          "country": "Estonia",
          "email": "implimentz@gmail.com",
          "twitter": "https://twitter.com/iamironz",
          "linkedIn": NaN,
          "github": "https://github.com/iamironz"
        },
      ]
    },
    {
      "id": "8",
      "description": "JKube : Kubernetes pour Javaiste qui n'aime pas le YAML",
      "heure": "10H30",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Sun",
          "username": "TAN",
          "companyPosition": "Senior Software Engineer",
          "company": "Red Hat",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Sun Tan.jpeg",
          "city": "Paris",
          "country": "France",
          "email": "sunix@sunix.org",
          "twitter": "https://twitter.com/__sunix_",
          "linkedIn": NaN,
          "github": "https://github.com/sunix"
        },
      ]
    },
    {
      "id": "9",
      "description": "Federated learning - A new paradigm to train a decentralized machine learning model",
      "heure": "10H30",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Xavier",
          "username": "LESSAGE",
          "companyPosition": "Sr Researcher (Artificial Intelligence / Cloud Computing)",
          "company": "CETIC",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Xavier Lessage.jpeg",
          "city": "Mons",
          "country": "Belgium",
          "email": "xavier.lessage@gmail.com",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": NaN
        },
      ]
    },
    {
      "id": "10",
      "description": "Frida as debugging tool for Android",
      "heure": "11H15",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Alexander",
          "username": "EFREMENKOV",
          "companyPosition": "Senior Android Engineer",
          "company": "Bolt",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/Alexander Efremenkov.jpeg",
          "city": "Tallinn",
          "country": "Estonia",
          "email": "implimentz@gmail.com",
          "twitter": "https://twitter.com/iamironz",
          "linkedIn": NaN,
          "github": "https://github.com/iamironz"
        },
      ]
    },
    {
      "id": "11",
      "description": "Cryptographie, hachage, chiffrement, sans les maths !",
      "heure": "11H15",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Cedric",
          "username": "GATAY",
          "companyPosition": "Mobile and backend developer",
          "company": "Code-Troopers",
          "GDE": "Non",
          "Charges": "Transport and Taxi",
          "picturePath": "assets/images/Cedric Gatay.webp",
          "city": "Tours",
          "country": "France",
          "email": "c.gatay@code-troopers.com",
          "twitter": "https://twitter.com/Cedric_Gatay",
          "linkedIn": NaN,
          "github": "https://github.com/CedricGatay"
        },
      ]
    },
    {
      "id": "12",
      "description": "Mutation Testing: Did my test break my code ?",
      "heure": "11H55",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Olivier",
          "username": "LEPLUS",
          "companyPosition": "Developer Relations",
          "company": "AWS",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/Olivier Leplus.jpeg",
          "city": "Paris",
          "country": "France",
          "email": "leplus.olivier@gmail.com",
          "twitter": "https://twitter.com/olivierleplus",
          "linkedIn": NaN,
          "github": "https://github.com/tagazok"
        },
        {
          "firstname": "Maha",
          "username": "ALSAYASNEH",
          "companyPosition": "Engineering Manager",
          "company": "Elastic",
          "GDE": "Non",
          "Charges": "Hotel & Transport",
          "picturePath": "assets/images/Maha ALSAYASNEH.jpeg",
          "city": "Grenoble",
          "country": "France",
          "email": "maha.alsayasneh@gmail.com",
          "twitter": "https://twitter.com/MahaALSayasneh",
          "linkedIn": NaN,
          "github": NaN
        },
      ]
    },
    {
      "id": "13",
      "description": "La sécurité, ce n'est pas que pour les Ops, \n" +
        "c'est aussi pour les Dev \n",
      "heure": "11H55",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Tugdual",
          "username": "GRALL",
          "companyPosition": "Solutions Engineer",
          "company": "GitHub",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Tugdual Grall.jpeg",
          "city": "Nantes",
          "country": "France",
          "email": "tugdual@gmail.com",
          "twitter": "https://twitter.com/tgrall",
          "linkedIn": NaN,
          "github": "https://github.com/tgrall"
        },
        {
          "firstname": "Adrien",
          "username": "PESSU",
          "companyPosition": "Auth0 developer advocate",
          "company": "Okta",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Adrien Pessu.jpeg",
          "city": "Nantes",
          "country": "France",
          "email": "apessu@gmail.com",
          "twitter": "https://twitter.com/adrienpessu",
          "linkedIn": NaN,
          "github": "https://github.com/@adrienpessu"
        },
      ]
    },
    {
      "id": "14",
      "description": "BREAK",
      "heure": "11H05",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "15",
      "description": "BREAK",
      "heure": "11H45",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "16",
      "description": "BREAK",
      "heure": "12H30",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "70px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "17",
      "description": "How To Review Someone's Code While Not Being A Jerk",
      "heure": "13H30",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Maha",
          "username": "ALSAYASNEH",
          "companyPosition": "Engineering Manager",
          "company": "Elastic",
          "GDE": "Non",
          "Charges": "Hotel & Transport",
          "picturePath": "assets/images/Maha ALSAYASNEH.jpeg",
          "city": "Grenoble",
          "country": "France",
          "email": "maha.alsayasneh@gmail.com",
          "twitter": "https://twitter.com/MahaALSayasneh",
          "linkedIn": NaN,
          "github": NaN
        },
      ]
    },
    {
      "id": "18",
      "description": "BREAK",
      "heure": "13H55",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "19",
      "description": "10 leçons sur les 10 plus grosses fuites de données",
      "heure": "14H05",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Adrien",
          "username": "PESSU",
          "companyPosition": "Auth0 developer advocate",
          "company": "Okta",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Adrien Pessu.jpeg",
          "city": "Nantes",
          "country": "France",
          "email": "apessu@gmail.com",
          "twitter": "https://twitter.com/adrienpessu",
          "linkedIn": NaN,
          "github": "https://github.com/@adrienpessu"
        },
      ]
    },
    {
      "id": "20",
      "description": "BREAK",
      "heure": "14H30",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "21",
      "description": "Recettes du développeur cloud responsable: go lean, go green",
      "heure": "14H40",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Philippe",
          "username": "DIDIERGEORGES",
          "companyPosition": "Founder",
          "company": "Bogglers Consulting",
          "GDE": "Non",
          "Charges": "HOTEL",
          "picturePath": "assets/images/Philippe Didiergeorges.jpeg",
          "city": "Strasbourg",
          "country": "France",
          "email": "philippe.didiergeorges@gmail.com",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": NaN
        },
        {
          "firstname": "Denis",
          "username": "VOITURON",
          "companyPosition": ".Net Senior developer",
          "company": "Microsoft",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Denis Voituron.jpeg",
          "city": "Ittre",
          "country": "Belgium",
          "email": "denis@voituron.net",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": NaN
        },
      ]
    },
    {
      "id": "22",
      "description": "BREAK",
      "heure": "15H05",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "23",
      "description": "Devenir un pro de l'UX en moins d'une heure",
      "heure": "13H30",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "150px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Nicolas",
          "username": "FRIZZARIN",
          "companyPosition": "Developer Advocate && Engineering Manager",
          "company": "SFEIR",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/nicolas Frizzarin.webp",
          "city": "Metz",
          "country": "France",
          "email": "nicolas.frizzarin54@gmail.com",
          "twitter": "https://twitter.com/Nicooss54",
          "linkedIn": NaN,
          "github": "https://github.com/Nicoss54"
        },
      ]
    },
    {
      "id": "24",
      "description": "Build your backend in Dart with Serverpod ",
      "heure": "13H30",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "150px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Viktor",
          "username": "LIDHOLT",
          "companyPosition": "Founder",
          "company": "Serverpod",
          "GDE": "Non",
          "Charges": "Hotel & Transport",
          "picturePath": "assets/images/viktor.jpeg",
          "city": "Stockolm",
          "country": "Sweden",
          "email": "viktorlidholt@gmail.com",
          "twitter": "https://twitter.com/viktorlidholt",
          "linkedIn": NaN,
          "github": "https://github.com/vlidholt"
        },
      ]
    },
    {
      "id": "25",
      "description": "BREAK",
      "heure": "14H10",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "26",
      "description": "Visual Testing Driven Development",
      "heure": "14H30",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "140px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Gerome",
          "username": "GRIGNON",
          "companyPosition": "Web developer",
          "company": "SFEIR",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Gerome Grignon.jpeg",
          "city": "Nantes",
          "country": "France",
          "email": "gerome.grignon.lp2@gmail.com",
          "twitter": "https://twitter.com/GeromeGrignon",
          "linkedIn": NaN,
          "github": "https://github.com/geromegrignon"
        },
      ]
    },
    {
      "id": "27",
      "description": "Building Flutter app for everyone\n",
      "heure": "14H30",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "140px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Aleksandr",
          "username": "DENISOV",
          "companyPosition": "Chief Software Engineer",
          "company": "EPAM Systems",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/Aleksandr Denisov.jpeg",
          "city": "Berlin",
          "country": "Germany",
          "email": "denisov.shureg@gmail.com",
          "twitter": "https://twitter.com/shuregdenisov",
          "linkedIn": NaN,
          "github": "https://github.com/denisovav"
        },
      ]
    },
    {
      "id": "28",
      "description": "sécurité + open source = ❤️",
      "heure": "15H15",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Adrien",
          "username": "PESSU",
          "companyPosition": "Auth0 developer advocate",
          "company": "Okta",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Adrien Pessu.jpeg",
          "city": "Nantes",
          "country": "France",
          "email": "apessu@gmail.com",
          "twitter": "https://twitter.com/adrienpessu",
          "linkedIn": NaN,
          "github": "https://github.com/@adrienpessu"
        },
      ]
    },
    {
      "id": "29",
      "description": "BREAK",
      "heure": "15H40",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "30",
      "description": "Codelab: Coder votre infrastructure avec votre langage préféré ! ",
      "heure": "15H50",
      "isTrackOne": true,
      "isTrackTwo": false,
      "isTrackTree": false,
      "height": "420px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Antoine",
          "username": "WACHEUX",
          "companyPosition": "Solutions architect",
          "company": "AWS",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Antoine Wacheux.jpeg",
          "city": "Paris",
          "country": "France",
          "email": "awacheux.utc@gmail.com",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": "https://github.com/shiroy"
        },
        {
          "firstname": "Olivier",
          "username": "LEPLUS",
          "companyPosition": "Developer Relations",
          "company": "AWS",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/Olivier Leplus.jpeg",
          "city": "Paris",
          "country": "France",
          "email": "leplus.olivier@gmail.com",
          "twitter": "https://twitter.com/olivierleplus",
          "linkedIn": NaN,
          "github": "https://github.com/tagazok"
        },
      ]
    },
    {
      "id": "31",
      "description": "Angular 14: The next generation of Angular Application",
      "heure": "15H15",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "130px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Nicolas",
          "username": "FRIZZARIN",
          "companyPosition": "Developer Advocate && Engineering Manager",
          "company": "SFEIR",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/nicolas Frizzarin.webp",
          "city": "Metz",
          "country": "France",
          "email": "nicolas.frizzarin54@gmail.com",
          "twitter": "https://twitter.com/Nicooss54",
          "linkedIn": NaN,
          "github": "https://github.com/Nicoss54"
        },
      ]
    },
    {
      "id": "32",
      "description": "Bases de données NoSQL Cloud Native - attention à la marche!",
      "heure": "15H15",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "130px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Philippe",
          "username": "DIDIERGEORGES",
          "companyPosition": "Founder",
          "company": "Bogglers Consulting",
          "GDE": "Non",
          "Charges": "HOTEL",
          "picturePath": "assets/images/Philippe Didiergeorges.jpeg",
          "city": "Strasbourg",
          "country": "France",
          "email": "philippe.didiergeorges@gmail.com",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": NaN
        },
      ]
    },
    {
      "id": "33",
      "description": "BREAK",
      "heure": "15H50",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "34",
      "description": "Quoi de neuf dans le monde du cache HTTP",
      "heure": "16H00",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Sylvain",
          "username": "COMBRAQUE",
          "companyPosition": "Go Consultant  | React JS",
          "company": "Freelance",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Sylvain COMBRAQUE.png",
          "city": "Paris",
          "country": "france",
          "email": "darkweak@protonmail.com",
          "twitter": "https://twitter.com/Darkweak_dev",
          "linkedIn": NaN,
          "github": "https://github.com/Darkweak"
        },
      ]
    },
    {
      "id": "35",
      "description": "GraalVM the revolution of Java Based Cloud Deployment",
      "heure": "16H00",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Loic",
          "username": "MAGNETTE",
          "companyPosition": "Solution Architect",
          "company": "Onyrix",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/loic magnette.jpeg",
          "city": "Seneffe",
          "country": "Belgium",
          "email": "loic.magnette@oniryx.be",
          "twitter": NaN,
          "linkedIn": NaN,
          "github": NaN
        }
      ]
    },
    {
      "id": "36",
      "description": "BREAK",
      "heure": "16H35",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "37",
      "description": "Vue 3 et son écosystème",
      "heure": "16H45",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Nicolas",
          "username": "FRIZZARIN",
          "companyPosition": "Developer Advocate && Engineering Manager",
          "company": "SFEIR",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/nicolas Frizzarin.webp",
          "city": "Metz",
          "country": "France",
          "email": "nicolas.frizzarin54@gmail.com",
          "twitter": "https://twitter.com/Nicooss54",
          "linkedIn": NaN,
          "github": "https://github.com/Nicoss54"
        },
      ]
    },
    {
      "id": "38",
      "description": "How I made a powerful cache system using Go",
      "heure": "16H45",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Sylvain",
          "username": "COMBRAQUE",
          "companyPosition": "Go Consultant  | React JS",
          "company": "Freelance",
          "GDE": "Non",
          "Charges": "Self",
          "picturePath": "assets/images/Sylvain COMBRAQUE.png",
          "city": "Paris",
          "country": "france",
          "email": "darkweak@protonmail.com",
          "twitter": "https://twitter.com/Darkweak_dev",
          "linkedIn": NaN,
          "github": "https://github.com/Darkweak"
        },
      ]
    },
    {
      "id": "39",
      "description": "BREAK",
      "heure": "17H10",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "40",
      "description": "Et si on faisait le tour de CORS ?",
      "heure": "17H20",
      "isTrackOne": false,
      "isTrackTwo": true,
      "isTrackTree": false,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Cedric",
          "username": "GATAY",
          "companyPosition": "Mobile and backend developer",
          "company": "Code-Troopers",
          "GDE": "Non",
          "Charges": "Transport and Taxi",
          "picturePath": "assets/images/Cedric Gatay.webp",
          "city": "Tours",
          "country": "France",
          "email": "c.gatay@code-troopers.com",
          "twitter": "https://twitter.com/Cedric_Gatay",
          "linkedIn": NaN,
          "github": "https://github.com/CedricGatay",
          "description":""
        },
      ]
    },
    {
      "id": "41",
      "description": "BREAK",
      "heure": "17H50",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "50px",
      "color": "grey",
      "isCard": false,
      "users": []
    },
    {
      "id": "42",
      "description": "JEU & WRAP UP",
      "heure": "18H00",
      "isTrackOne": true,
      "isTrackTwo": true,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": []
    },
    {
      "id": "43",
      "description": "Cloud functions width firebase",
      "heure": "17H20",
      "isTrackOne": false,
      "isTrackTwo": false,
      "isTrackTree": true,
      "height": "80px",
      "color": "#ffd180",
      "isCard": true,
      "users": [
        {
          "firstname": "Renaud",
          "username": "TARNEC",
          "companyPosition": "Consultant",
          "company": "Freelance",
          "GDE": "Oui",
          "Charges": "OK",
          "picturePath": "assets/images/Renaud Tarnec.jpeg",
          "city": "Brussels",
          "country": "Belgium",
          "email": "renaudtarnec@gmail.com",
          "twitter": "https://twitter.com/rtarnec",
          "linkedIn": "https://www.linkedin.com/in/renaudtarnec/",
          "github": "",
          "description":""
        }
      ]
    },
  ]
}
