export const speakers = {
users : [
    {
        "firstname": "Aleksandr",
        "username": "DENISOV",
        "companyPosition": "Chief Software Engineer",
        "company": "EPAM Systems",
        "GDE": "Oui",
        "Charges": "OK",
        "picturePath": "assets/images/Aleksandr Denisov.jpeg",
        "city": "Berlin",
        "country": "Germany",
        "email": "denisov.shureg@gmail.com",
        "twitter": "https://twitter.com/shuregdenisov",
        "linkedIn": NaN,
        "github": "https://github.com/denisovav",
        "description": "Based in Tallinn, Estonia, Aleksandr, he is GDE Estonia member and working on the Android stack core solutions that millions of European people use. Digger inside the Android platform and is always trying to understand how systems work from the inside. Part-time open source writer and conference speaker, mostly talking about Android internals and system layer."
    },
    {
        "firstname": "Nicolas",
        "username": "FRIZZARIN",
        "companyPosition": "Developer Advocate && Engineering Manager",
        "company": "SFEIR",
        "GDE": "Oui",
        "Charges": "OK",
        "picturePath": "assets/images/nicolas Frizzarin.webp",
        "city": "Metz",
        "country": "France",
        "email": "nicolas.frizzarin54@gmail.com",
        "twitter": "https://twitter.com/Nicooss54",
        "linkedIn": NaN,
        "github": "https://github.com/Nicoss54",
        "description": "Google Developer Expert in Web Technologies and OpenJs Foundation Member, Nicolas is a FontEnd specialist and user Interface Designer from Metz, France.\n\nHe works as a developer advocate and Engineering Manager at Sfeir Luxembourg. His daily mission is to help the teams to make robust, powerful and beautiful web applications\n\nBesides that, Nicolas is a speaker, and likes to contribute to the community by giving talks, trainings, writing articles or participating in open source projects"
    },
    {
        "firstname": "Adrien",
        "username": "PESSU",
        "companyPosition": "Auth0 developer advocate",
        "company": "Okta",
        "GDE": "Non",
        "Charges": "Self",
        "picturePath": "assets/images/Adrien Pessu.jpeg",
        "city": "Nantes",
        "country": "France",
        "email": "apessu@gmail.com",
        "twitter": "https://twitter.com/adrienpessu",
        "linkedIn": NaN,
        "github": "https://github.com/@adrienpessu",
        "description": "Je suis un d\u00e9veloppeur fullstack depuis 14 ans et je viens de Nantes. Je suis \u00e9galement membre organisateur et tr\u00e9sorier de l'association Blockchain & Soci\u00e9t\u00e9 : https://blockchainsociete.org/ Nous organisons des meetups autours de la blockchain et des cryptos\n\nDe nature tr\u00e8s curieux, j'adore \u00e9chang\u00e9 avec mes pairs et toujours en apprendre plus. Je trouve que je suis dans un secteur passionnant qui tend souvent au changement, c'est tr\u00e8s enrichissant intellectuellement."
    },
    {
        "firstname": "Philippe",
        "username": "DIDIERGEORGES",
        "companyPosition": "Founder",
        "company": "Bogglers Consulting",
        "GDE": "Non",
        "Charges": "HOTEL",
        "picturePath": "assets/images/Philippe Didiergeorges.jpeg",
        "city": "Strasbourg",
        "country": "France",
        "email": "philippe.didiergeorges@gmail.com",
        "twitter": NaN,
        "linkedIn": NaN,
        "github": NaN,
        "description": "NaN"
    },
    {
        "firstname": "Olivier",
        "username": "LEPLUS",
        "companyPosition": "Developer Relations",
        "company": "AWS",
        "GDE": "Oui",
        "Charges": "OK",
        "picturePath": "assets/images/Olivier Leplus.jpeg",
        "city": "Paris",
        "country": "France",
        "email": "leplus.olivier@gmail.com",
        "twitter": "https://twitter.com/olivierleplus",
        "linkedIn": NaN,
        "github": "https://github.com/tagazok",
        "description": "Developer Advocate at AWS and Google Developer Expert in Web Technologies. I love to share knowledge (and love) among developers and people in general."
    },
    {
        "firstname": "Gerome",
        "username": "GRIGNON",
        "companyPosition": "Web developer",
        "company": "SFEIR",
        "GDE": "Non",
        "Charges": "Self",
        "picturePath": "assets/images/Gerome Grignon.jpeg",
        "city": "Nantes",
        "country": "France",
        "email": "gerome.grignon.lp2@gmail.com",
        "twitter": "https://twitter.com/GeromeGrignon",
        "linkedIn": NaN,
        "github": "https://github.com/geromegrignon"
    },
    {
        "firstname": "Neil",
        "username": "GIBBONS",
        "companyPosition": "Backend Engineer",
        "company": "EDITED",
        "GDE": "Non",
        "Charges": "110\u20ac",
        "picturePath": "assets/images/Neil Gibbons.jpeg",
        "city": "London",
        "country": "UK",
        "email": "neil.gibbons64@gmail.com",
        "twitter": NaN,
        "linkedIn": NaN,
        "github": "https://github.com/nyptop",
        "description": "Neil is a Backend Engineer based in London. He works for EDITED, a platform which helps retailers make data-driven decisions. Outside of work, Neil hosts the London Tech Insider podcast, interviewing developers, academics and investors from across London\u2019s tech ecosystem. He is also an enthusiastic runner!"
    },
    {
        "firstname": "Alexander",
        "username": "EFREMENKOV",
        "companyPosition": "Senior Android Engineer",
        "company": "Bolt",
        "GDE": "Oui",
        "Charges": "OK",
        "picturePath": "assets/images/Alexander Efremenkov.jpeg",
        "city": "Tallinn",
        "country": "Estonia",
        "email": "implimentz@gmail.com",
        "twitter": "https://twitter.com/iamironz",
        "linkedIn": NaN,
        "github": "https://github.com/iamironz"
    },
    {
        "firstname": "Viktor",
        "username": "LIDHOLT",
        "companyPosition": "Founder",
        "company": "Serverpod",
        "GDE": "Non",
        "Charges": "Hotel & Transport",
        "picturePath": "assets/images/viktor.jpeg",
        "city": "Stockolm",
        "country": "Sweden",
        "email": "viktorlidholt@gmail.com",
        "twitter": "https://twitter.com/viktorlidholt",
        "linkedIn": NaN,
        "github": "https://github.com/vlidholt",
        "description": "With a master\u2019s in computer science and more than 20 years of industry experience, Viktor has a solid background in software engineering. Before starting his own venture, he worked at Google\u2019s Flutter team in Silicon Valley. He has held talks and taught guest lectures on programming, app creation, and computer graphics at international conferences and universities such as MIT, Carnegie Mellon, and UC Berkeley."
    },
    {
        "firstname": "Maha",
        "username": "ALSAYASNEH",
        "companyPosition": "Engineering Manager",
        "company": "Elastic",
        "GDE": "Non",
        "Charges": "Hotel & Transport",
        "picturePath": "assets/images/Maha ALSAYASNEH.jpeg",
        "city": "Grenoble",
        "country": "France",
        "email": "maha.alsayasneh@gmail.com",
        "twitter": "https://twitter.com/MahaALSayasneh",
        "linkedIn": NaN,
        "github": NaN,
        "description": "I am a computer scientist with more than 10 years of experience in various fields ranging from web development to big data, including cloud\ncomputing and artificial intelligence. My experience combines technical and analytical aptitudes with problem-solving strengths to\ndrive projects to on-time and high-quality completion. \n\nI also have a Ph.D. in optimizing the performance of multi-tier distributed systems.\n\nCurrently, I am an Engineering Manager at Elastic. We are the leading platform for search-powered solutions.\n\nI love communicating and sharing knowledge  with people ;) ( I also love sports and mountains ;) )\n\nMy motto in life is LIVE + LOVE + LAUGH :)\n\n\n"
    },
    {
        "firstname": "Sylvain",
        "username": "COMBRAQUE",
        "companyPosition": "Go Consultant  | React JS",
        "company": "Freelance",
        "GDE": "Non",
        "Charges": "Self",
        "picturePath": "assets/images/Sylvain COMBRAQUE.png",
        "city": "Paris",
        "country": "france",
        "email": "darkweak@protonmail.com",
        "twitter": "https://twitter.com/Darkweak_dev",
        "linkedIn": NaN,
        "github": "https://github.com/Darkweak",
        "description": "Golang developer, creator of [Souin](https://github.com/darkweak/souin) and active contributor for [Caddy](https://github.com/caddyserver), [Tr\u00e6fik](https://github.com/traefik) and [API Platform](https://github.com/api-platform)"
    },
    {
        "firstname": "Antoine",
        "username": "WACHEUX",
        "companyPosition": "Solutions architect",
        "company": "AWS",
        "GDE": "Non",
        "Charges": "Self",
        "picturePath": "assets/images/Antoine Wacheux.jpeg",
        "city": "Paris",
        "country": "France",
        "email": "awacheux.utc@gmail.com",
        "twitter": NaN,
        "linkedIn": NaN,
        "github": "https://github.com/shiroy",
        "description": "If you ask me why I got into IT, I'd say it was a natural path for me.\n\nAs a kid, I discovered it as a hobby. I wanted to be like these cool hackers in movies. I still remember my very first programming language: `QBasic`.  The internet is like a massive free university. I had so much fun learning `C`, `C++`, and `PHP`and working on tons of fun hobby projects at that time!\n\nNaturally, I've been through a computer engineering degree at UTC, Compi\u00e8gne, France. It was tough but enlightening. I had skills in different domains and this degree brought all the pieces together.\n\nMy first job as a software engineer at Bloomberg LP, London, was very challenging but it felt weird at the same time. The company, the people and the projects were awesome but I couldn't get used to professional software development. It was too different to what I used to like as a hobby. Maybe this job was not for me.\n\nIn 2018, cloud computing was trending and I had no experience with it. I joined D2SI (now Devoteam Revolve) as a junior cloud computing consultant where I worked on many different and challenging projects. As a consultant, I was the knowledgable guy. I discovered that I love teaching!\n\nFinally, I had the opportunity to join AWS in 2020 as a Solutions Architect. I discover the business world thanks to this position. It's an awesome role to hone my business and teaching skills.\n\nNow here I am! I can't wait to share what I learned with you!"
    },
    {
        "firstname": "Denis",
        "username": "VOITURON",
        "companyPosition": ".Net Senior developer",
        "company": "Microsoft",
        "GDE": "Non",
        "Charges": "Self",
        "picturePath": "assets/images/Denis Voituron.jpeg",
        "city": "Ittre",
        "country": "Belgium",
        "email": "denis@voituron.net",
        "twitter": NaN,
        "linkedIn": NaN,
        "github": NaN,
        "description": "Aleksandr is an experienced software developer with a rich background, in IT for more than 20 years. He worked with different stacks in backend, frontend and mobile fields, but since 2018 his main interest is Flutter. Aleksandr is a Flutter and Dart GDE and Head of Flutter Discipline in EPAM Systems."
    },
    {
        "firstname": "Loic",
        "username": "MAGNETTE",
        "companyPosition": "Solution Architect",
        "company": "Onyrix",
        "GDE": "Non",
        "Charges": "Self",
        "picturePath": "assets/images/loic magnette.jpeg",
        "city": "Seneffe",
        "country": "Belgium",
        "email": "loic.magnette@oniryx.be",
        "twitter": NaN,
        "linkedIn": NaN,
        "github": NaN
    }
]
}